# Site settings
title: encyclomap
email: tutecosta@gmail.com
description: "Discover the world around you"
baseurl: "/encyclomap/"
url: "https://www.tutecosta.com" # the base hostname & protocol for your site
twitter_username: tutec
github_username: tute

# Build settings
markdown: kramdown
